### ISSUE TITLE
Is anyone still using this? Is it still working?

### ISSUE THREAD

**Issue by danieljimenez** [ConradIrwin/aws-name-server#16]
I've been thinking of something like this and would be a heavy user. Right now I have a script that I run on EC2 instances that registers them with route53, but this dynamic lookup would be even more handy.

**Comment by ConradIrwin** [comment]
I know of a few people using it, but I'm personally currently running
everything on google cloud (which has this feature built in :p).

Not sure how "heavy" existing users are (feel free to chime in), but I know
a few people using it for making SSH'ing to production easier (even if
they're not using it as a service discovery mechanism).

Definitely happy to provide support if you need help getting up and running.

Sent via Superhuman <https://sprh.mn/?vip=conrad@superhuman.com>

**Comment by danieljimenez** [comment]
Awesome, thanks for the message. I'd mostly be using it for that. I really wish Amazon would offer that feature, or at least a way to build it with Lambda and cloudfront.

Thanks for the input!
